title: Clickbait Stories
email: dave@dfbr.co.uk
description: >-
  Daily AI-generated uplifting clickbait stories
baseurl: "/clickbait_generator"
url: "https://dfbr.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:categories/:year/:month/:day/:title.html
collections:
  posts:
    output: true
    permalink: /articles/:year/:month/:day/:title.html
