title: Clickbait Stories
email: your-email@example.com
description: >-
  Daily AI-generated uplifting clickbait stories
baseurl: ""
url: ""
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:categories/:year/:month/:day/:title.html
collections:
  posts:
    output: true
    permalink: /articles/:year/:month/:day/:title.html
